/**
 * How to actually fix each failure, per platform.
 *
 * A finding without a fix is a complaint. Every recipe here is concrete enough
 * that a developer can act on it without opening a spec, and platform notes
 * exist because "add an alt attribute" is unhelpful advice to someone whose
 * markup is generated by a Shopify theme they cannot edit directly.
 */

export type PlatformId =
  | 'html'
  | 'shopify'
  | 'wordpress'
  | 'webflow'
  | 'squarespace'
  | 'wix'
  | 'react'
  | 'drupal';

export interface Platform {
  readonly id: PlatformId;
  readonly name: string;
  /** Where a non-developer goes to make the change. */
  readonly editSurface: string;
}

export const PLATFORMS: readonly Platform[] = [
  { id: 'html', name: 'Plain HTML', editSurface: 'the page source' },
  { id: 'shopify', name: 'Shopify', editSurface: 'Online Store → Themes → Edit code, and the product admin' },
  { id: 'wordpress', name: 'WordPress', editSurface: 'the block editor, the Media Library, and your theme templates' },
  { id: 'webflow', name: 'Webflow', editSurface: 'the Designer element settings panel' },
  { id: 'squarespace', name: 'Squarespace', editSurface: 'the page editor and site styles' },
  { id: 'wix', name: 'Wix', editSurface: 'the Editor element settings' },
  { id: 'react', name: 'React and Next.js', editSurface: 'your component source' },
  { id: 'drupal', name: 'Drupal', editSurface: 'Twig templates and field settings' },
] as const;

export const platformById = (id: PlatformId): Platform | undefined =>
  PLATFORMS.find((p) => p.id === id);

export type Effort = 'minutes' | 'hours' | 'days';

export interface Recipe {
  /** axe rule id this fixes. */
  readonly ruleId: string;
  /** Human title, used as the page heading in the fix guides. */
  readonly title: string;
  /** What is actually wrong, in one sentence, without jargon. */
  readonly problem: string;
  /** Who it affects and how. */
  readonly impact: string;
  /** The general fix, platform-independent. */
  readonly fix: readonly string[];
  readonly wrong?: string;
  readonly right?: string;
  readonly effort: Effort;
  /** Mistakes that create a second failure while fixing the first. */
  readonly pitfalls: readonly string[];
  readonly platformNotes: Partial<Record<PlatformId, string>>;
}

export const RECIPES: readonly Recipe[] = [
  {
    ruleId: 'image-alt',
    title: 'Images without alternative text',
    problem: 'An <img> element has no alt attribute, so assistive technology has nothing to announce and falls back to reading the file name.',
    impact: 'A screen reader user hears "IMG_4471 dot jpg" instead of "Navy wool overcoat". Where the image is the only content of a link, the destination becomes unknowable and navigation breaks entirely.',
    fix: [
      'Decide what the image is doing. If it carries information, describe that information. If it is decoration, mark it as decoration.',
      'For informative images, write alt text that conveys the same thing the image conveys — not a description of the picture. For a product photo, the product name. For a chart, the finding.',
      'For decorative images, use alt="" — an empty attribute, present but blank. This tells assistive technology to skip it. Omitting the attribute entirely is not the same thing.',
      'For an image that is the only content of a link or button, the alt text must describe the destination or action, not the picture.',
    ],
    wrong: '<a href="/cart"><img src="cart-icon.svg"></a>',
    right: '<a href="/cart"><img src="cart-icon.svg" alt="Shopping cart, 3 items"></a>',
    effort: 'hours',
    pitfalls: [
      'Do not start alt text with "image of" or "picture of" — screen readers already announce that it is an image.',
      'Do not stuff keywords into alt text. It is read aloud in full, and it is the fastest way to make a page hostile to the people it is meant to help.',
      'An empty alt="" on an image that carries meaning is a failure, not a fix. It hides real content.',
    ],
    platformNotes: {
      shopify: 'Product images take alt text in Products → the image → "Add alt text". Theme-level images are usually in a section schema; in Liquid, `{{ image | image_tag: alt: image.alt }}` carries it through. Many themes emit `alt=""` for every section image by default — check the section files, not just the admin.',
      wordpress: 'Set alt text in the Media Library, which applies wherever the image is reused. Block-level overrides live in the image block sidebar. Beware page builders that render images as CSS backgrounds — those cannot carry alt text and need real <img> elements.',
      webflow: 'Select the image, open Settings, and set Alt Text. Choose "decorative" for images that carry no information — Webflow emits alt="" for that. CMS-bound images need an alt field on the Collection, otherwise every item inherits one string.',
      squarespace: 'The filename becomes the alt text by default, which is why so many Squarespace sites announce filenames. Set it per image in the image block, or clear it for decorative images.',
      wix: 'Right-click the image → Settings → "What\'s in the image? Tell Google". That field is the alt attribute despite the name.',
      react: 'The alt prop is required on <img> by eslint-plugin-jsx-a11y. Turn on `jsx-a11y/alt-text` in CI so this cannot regress. next/image takes the same prop and enforces it.',
      drupal: 'Alt text is a field property on image fields; make it required in the field settings. Twig: `{{ content.field_image }}` carries it, but custom `<img>` in templates does not.',
    },
  },
  {
    ruleId: 'color-contrast',
    title: 'Text with insufficient colour contrast',
    problem: 'Foreground and background colours are too close together to meet the 4.5:1 minimum for body text, or 3:1 for text at 18pt and above or 14pt bold and above.',
    impact: 'This is the most widespread failure on the web, present on 83.9% of home pages. It affects everyone with low vision, everyone over about fifty, and every user in sunlight. Grey-on-white body text and light-grey placeholder text are the usual offenders.',
    fix: [
      'Measure the real computed colours, not the ones in the design file — opacity, overlays and inherited colours change the result.',
      'Darken the foreground or lighten the background until body text reaches 4.5:1. Large text (24px, or 19px bold) needs 3:1.',
      'Fix the token, not the instance. Almost every contrast failure traces back to one or two palette values used in hundreds of places.',
      'Check the states as well as the resting style: hover, focus, visited, disabled, placeholder, and text over images.',
    ],
    wrong: '.muted { color: #999; background: #fff; } /* 2.85:1 — fails */',
    right: '.muted { color: #767676; background: #fff; } /* 4.54:1 — passes */',
    effort: 'hours',
    pitfalls: [
      'Placeholder text is text. Grey placeholders at #ccc are one of the most common failures found in checkout forms.',
      'Text over a photograph must meet the ratio against the actual pixels behind it. A scrim or solid backing plate is the reliable fix.',
      'Disabled controls are exempt from 1.4.3, but a control that merely looks disabled and is not actually disabled is a failure.',
    ],
    platformNotes: {
      shopify: 'Most themes expose colour settings under Theme settings → Colors, which is where to fix it globally. Dawn-derived themes use CSS custom properties like `--color-foreground`; change those rather than adding overrides.',
      wordpress: 'Full-site-editing themes define colours in theme.json under `settings.color.palette`. Change the palette entry so every block using that slug is fixed at once.',
      webflow: 'Fix the swatch in the Style panel, not individual elements — Webflow global swatches propagate everywhere they are used.',
      squarespace: 'Site Styles → Colors defines section themes. Edit the theme rather than adding custom CSS, or the change will not survive template updates.',
      wix: 'Site Design → Colors edits the palette. Wix text elements often carry inline colours that override the palette; check the element itself if the change does not take.',
      react: 'Put the ratio in a test. `jest-axe` or `@axe-core/playwright` in CI will catch a palette regression before it ships.',
      drupal: 'Colours usually live in the theme\'s CSS custom properties or a base theme\'s SCSS variables.',
    },
  },
  {
    ruleId: 'label',
    title: 'Form fields without labels',
    problem: 'An input, select or textarea has no programmatically associated label, so assistive technology cannot say what it is for.',
    impact: 'A screen reader announces "edit, blank". The user cannot tell whether the field wants an email address, a postcode, or a card number. On a checkout form this is the fact pattern behind a large share of filed complaints.',
    fix: [
      'Give the input an id and point a <label for="..."> at it. This is the most robust option and it also makes the label clickable, which helps everyone.',
      'Where a visible label is genuinely impossible, use aria-label on the input, or aria-labelledby pointing at existing visible text.',
      'Never rely on placeholder alone. Placeholder text disappears the moment the user types, and several screen reader and browser combinations do not announce it at all.',
      'Group related controls — radio sets, address blocks — in a <fieldset> with a <legend>.',
    ],
    wrong: '<input type="email" placeholder="Email address">',
    right: '<label for="email">Email address</label>\n<input type="email" id="email" name="email" autocomplete="email">',
    effort: 'hours',
    pitfalls: [
      'A <label> that wraps an input but has no `for` still works — but only if it wraps exactly one control.',
      'aria-label overrides visible text. If the visible label says "Email" and aria-label says "Enter your email", voice control users saying "click Email" may fail. Keep the visible text inside the accessible name (WCAG 2.5.3).',
      'Duplicate ids silently break the association. This is the most common cause of a label that looks correct and is not.',
    ],
    platformNotes: {
      shopify: 'Contact and newsletter forms come from theme snippets; the label is usually there but visually hidden with a class. Check that the hiding technique is a clip-rect utility and not `display:none`, which removes it from the accessibility tree entirely.',
      wordpress: 'Contact Form 7 and Gravity Forms both emit labels, but many themes hide them with CSS. Gravity Forms has a per-field "Label Visibility" setting — "hidden" there is accessible, `display:none` in CSS is not.',
      webflow: 'The Form Label element binds automatically to the input it sits with. Deleting the label element to save space is the usual cause.',
      squarespace: 'Form block fields render labels by default; the "Lightweight" style hides them. Prefer the standard style, or add aria-label via code injection.',
      wix: 'Each input\'s Settings panel has a label field, plus a separate "Hide label" toggle. Hiding it in the editor removes it from the DOM entirely.',
      react: 'Use htmlFor, not for. Generate ids with `useId()` so repeated form components never collide. Enable `jsx-a11y/label-has-associated-control`.',
      drupal: 'The Form API emits labels automatically; `#title_display: invisible` hides them accessibly, while custom Twig templates that drop `{{ label }}` do not.',
    },
  },
  {
    ruleId: 'link-name',
    title: 'Links with no discernible text',
    problem: 'An anchor has no text content, no accessible name from an image alt, and no aria-label — so there is nothing to announce.',
    impact: 'Screen reader users navigate by pulling up a list of every link on the page. An unnamed link appears in that list as "link", or as a raw URL. Icon-only social links and image-wrapped logo links are the usual causes.',
    fix: [
      'Put real text inside the link. If it must look like an icon only, keep the text and hide it visually with a clip utility class that leaves it in the accessibility tree.',
      'For a link wrapping only an image, give the image alt text describing the destination.',
      'For an SVG icon inside a link, add aria-label to the anchor and aria-hidden="true" to the SVG so the icon is not announced twice.',
      'Write the name to describe the destination. "Read more" repeated eleven times is technically named and practically useless (WCAG 2.4.4).',
    ],
    wrong: '<a href="/x"><svg viewBox="0 0 24 24"><path d="..."/></svg></a>',
    right: '<a href="/x" aria-label="Our profile on X">\n  <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="..."/></svg>\n</a>',
    effort: 'minutes',
    pitfalls: [
      'Do not use `display:none` or `visibility:hidden` to hide link text — both remove it from the accessibility tree, which is the failure you are trying to fix.',
      'title="" is not a reliable accessible name. It is not announced by every screen reader and never appears on touch.',
      'An empty anchor used as a scroll target (<a id="section"></a>) is fine, but give it no href.',
    ],
    platformNotes: {
      shopify: 'Social icon links in theme footers are the usual source. In Dawn-based themes look for `snippets/social-icons.liquid` and confirm each anchor carries a `<span class="visually-hidden">`.',
      wordpress: 'The Social Icons block emits labels; hand-coded footer icons in a child theme usually do not.',
      webflow: 'Add the text inside the link block and apply Webflow\'s built-in "sr-only" style, or set an aria-label through the element\'s custom attributes.',
      squarespace: 'Social link blocks handle this correctly. Custom code blocks with raw SVGs do not.',
      wix: 'Set the link\'s "Accessibility" → "Name" field in the settings panel.',
      react: 'Icon components should require an `aria-label` prop when rendered inside an anchor. `jsx-a11y/anchor-has-content` catches the empty case.',
      drupal: 'Check custom Twig for `<a>{{ icon }}</a>` patterns with no text fallback.',
    },
  },
  {
    ruleId: 'button-name',
    title: 'Buttons with no accessible name',
    problem: 'A <button>, or an element with role="button", has no text, no aria-label and no labelled content.',
    impact: 'The control is announced as "button" with no indication of what it does. Close buttons on modals, hamburger menus, carousel arrows and icon-only cart buttons are the common cases — and a modal that cannot be closed is a hard block.',
    fix: [
      'Put text in the button, visually hidden if the design requires an icon only.',
      'Or set aria-label on the button element itself, describing the action rather than the icon: "Close dialog", not "X".',
      'Mark decorative icons inside the button aria-hidden="true".',
      'If the control changes state, add aria-expanded or aria-pressed so the state is announced too.',
    ],
    wrong: '<button class="close">&times;</button>',
    right: '<button class="close" aria-label="Close dialog">\n  <span aria-hidden="true">&times;</span>\n</button>',
    effort: 'minutes',
    pitfalls: [
      'A &times; or an icon-font glyph is not text. Icon fonts often announce as nothing, or as a meaningless character.',
      'A <div onclick> is not a button. It needs role="button", tabindex="0", and Enter and Space handlers — using a real <button> gets all of that for free.',
      'Name the action, not the appearance. "Menu" is a better name than "Hamburger".',
    ],
    platformNotes: {
      shopify: 'Cart drawer and mobile menu toggles in theme headers. Dawn ships accessible versions; heavily customised themes often strip the hidden text.',
      wordpress: 'Theme mobile-menu toggles, and lightbox close buttons added by gallery plugins.',
      webflow: 'Interactions-driven toggles are usually div elements. Set the element tag to Button in settings, then add the aria-label.',
      squarespace: 'Custom code blocks and third-party popup scripts are the usual source.',
      wix: 'Set the button\'s accessibility name in the settings panel; the visible icon is separate.',
      react: 'Prefer <button type="button"> over a clickable div in every case. `jsx-a11y/control-has-associated-label` enforces the name.',
      drupal: 'Check custom JS that builds controls at runtime — those bypass the Form API entirely.',
    },
  },
  {
    ruleId: 'html-has-lang',
    title: 'Page with no language declared',
    problem: 'The <html> element has no lang attribute, so nothing tells assistive technology which language the page is in.',
    impact: 'A screen reader reads the page in whatever voice it defaults to. English read with a Spanish synthesiser is not merely awkward — it is frequently unintelligible. This is a one-line fix that takes seconds and appears on 13.5% of home pages.',
    fix: [
      'Add a lang attribute with a valid BCP 47 tag to the <html> element: <html lang="en">.',
      'Use a region only when it matters for pronunciation or spelling — "en-GB" or "pt-BR" are meaningful; "en-US" is usually unnecessary.',
      'Mark passages in another language inline with lang on the surrounding element (WCAG 3.1.2).',
    ],
    wrong: '<html>',
    right: '<html lang="en">',
    effort: 'minutes',
    pitfalls: [
      'lang="EN_US" is invalid. The separator is a hyphen and the tag must be a registered subtag.',
      'Setting lang on <body> instead of <html> does not satisfy the criterion.',
      'A multilingual site must change the attribute per rendered language, not hard-code one.',
    ],
    platformNotes: {
      shopify: '`<html lang="{{ request.locale.iso_code }}">` in layout/theme.liquid handles multi-market stores correctly.',
      wordpress: '`<html <?php language_attributes(); ?>>` in header.php. Themes that hard-code `<html>` are the usual cause.',
      webflow: 'Set it in Site Settings → General → Language, which writes the attribute for you.',
      squarespace: 'Set under Settings → Language & Region.',
      wix: 'Set in Settings → Language & Region.',
      react: 'In Next.js App Router, `<html lang="en">` in app/layout.tsx. In Pages Router, set it in _document.tsx.',
      drupal: 'Handled by the language module; check that custom `html.html.twig` keeps `{{ html_attributes }}`.',
    },
  },
  {
    ruleId: 'aria-required-attr',
    title: 'ARIA roles missing their required attributes',
    problem: 'An element declares an ARIA role but omits an attribute that role requires — a checkbox with no aria-checked, a slider with no aria-valuenow.',
    impact: 'The control is announced with the wrong state or no state at all. A custom checkbox that never reports whether it is checked makes a form impossible to complete reliably.',
    fix: [
      'Look up the role in the ARIA specification and supply every required attribute.',
      'Keep the attribute in sync with the visual state in JavaScript — setting it once at render is a common and silent bug.',
      'Prefer the native element. <input type="checkbox"> needs no ARIA at all and cannot fall out of sync.',
    ],
    wrong: '<div role="checkbox" tabindex="0" class="cb"></div>',
    right: '<input type="checkbox" id="terms">\n<label for="terms">I accept the terms</label>',
    effort: 'hours',
    pitfalls: [
      'No ARIA is better than bad ARIA. A wrong role actively misinforms; a missing one merely under-informs.',
      'Adding a role does not add behaviour. role="button" gives you no keyboard handling.',
    ],
    platformNotes: {
      react: 'Headless component libraries (Radix, React Aria, Headless UI) implement these patterns correctly. Reimplementing them by hand is the usual source of this failure.',
      html: 'The ARIA Authoring Practices Guide gives a correct reference implementation for each pattern.',
    },
  },
  {
    ruleId: 'bypass',
    title: 'No way to skip repeated navigation',
    problem: 'The page offers no skip link, and no landmark or heading structure that would let a user jump past the header and navigation.',
    impact: 'A screen reader or keyboard user has to tab through every navigation link on every page before reaching the content. On a site with a forty-item mega-menu that is forty keystrokes per page.',
    fix: [
      'Add a skip link as the first focusable element: <a class="skip" href="#main">Skip to main content</a>.',
      'Give it a real target: <main id="main" tabindex="-1">.',
      'Style it off-screen until focused, then bring it into view. It must become visible on focus — a permanently invisible skip link fails.',
      'Use landmark elements — <header>, <nav>, <main>, <footer> — which give assistive technology a second way to jump.',
    ],
    wrong: '<body>\n  <nav>…40 links…</nav>\n  <div class="content">',
    right: '<body>\n  <a href="#main" class="skip-link">Skip to main content</a>\n  <header><nav>…</nav></header>\n  <main id="main" tabindex="-1">',
    effort: 'minutes',
    pitfalls: [
      'The skip link must be the first thing in the tab order. Placing it after the logo defeats it.',
      '`.skip-link { display:none }` removes it from the tab order entirely. Use a clip-based visually-hidden utility that reveals on :focus.',
      'Without tabindex="-1" on the target, some browsers move the viewport but not the focus.',
    ],
    platformNotes: {
      shopify: 'Dawn ships a working skip link in layout/theme.liquid. Custom themes often drop it.',
      wordpress: 'Themes supporting the `skip-link` feature emit one automatically; block themes need it in the template.',
      webflow: 'Add a link block as the very first element in the body, with an ID target on the main section.',
      react: 'Render it first in the layout, and move focus to the target on route change so it works in a single-page app.',
    },
  },
  {
    ruleId: 'document-title',
    title: 'Page with no title',
    problem: 'The document has no <title>, or the title is empty.',
    impact: 'Screen readers announce the title first when a page loads. Without it, a user has no idea where they have landed, and browser tabs and history entries become indistinguishable.',
    fix: [
      'Give every page a unique, descriptive <title>.',
      'Put the specific part first: "Checkout — Acme" beats "Acme — Checkout" when the tab is narrow.',
      'In a single-page app, update the title on every route change and announce it.',
    ],
    wrong: '<title></title>',
    right: '<title>Checkout — Acme Supply Co.</title>',
    effort: 'minutes',
    pitfalls: [
      'Identical titles across pages technically pass this rule but fail the intent, and break history navigation.',
      'Client-side routers do not update the title unless told to.',
    ],
    platformNotes: {
      react: 'Next.js App Router: export `metadata` from the page. Pages Router: use next/head.',
      shopify: '`{{ page_title }}` in layout/theme.liquid.',
      wordpress: 'Ensure the theme calls `add_theme_support( "title-tag" )`.',
    },
  },
  {
    ruleId: 'aria-input-field-name',
    title: 'ARIA input fields with no accessible name',
    problem: 'An element with an ARIA input role — combobox, listbox, searchbox, slider, spinbutton — has no accessible name.',
    impact: 'Custom dropdowns and autocompletes are announced as "combobox" with no indication of what they select. Country pickers, quantity selectors and date fields are the frequent cases.',
    fix: [
      'Add aria-label, or aria-labelledby pointing at the visible label.',
      'Where a real <label> and native control can be used instead, use them.',
      'Confirm the name in a browser accessibility inspector rather than assuming the attribute took effect.',
    ],
    effort: 'hours',
    pitfalls: [
      'aria-labelledby must reference an id that exists on the page. A typo fails silently.',
      'A custom combobox needs far more than a name — aria-expanded, aria-controls, aria-activedescendant and keyboard handling all have to be right.',
    ],
    platformNotes: {
      react: 'Use a headless combobox implementation rather than building one. This pattern is very difficult to get right by hand.',
    },
  },
  {
    ruleId: 'frame-title',
    title: 'Iframes with no title',
    problem: 'An <iframe> has no title attribute, so it is announced only as "frame".',
    impact: 'Screen reader users navigating by frame cannot tell an embedded video from a payment form from a tracking pixel. Payment iframes are the case that matters — an unnamed one makes checkout opaque.',
    fix: [
      'Add a title describing what the frame contains: title="Payment card details" or title="Product demonstration video".',
      'Where the frame is purely decorative or invisible — a tracking pixel — mark it aria-hidden="true" and remove it from the tab order.',
    ],
    wrong: '<iframe src="https://player.example/abc"></iframe>',
    right: '<iframe src="https://player.example/abc" title="How to fit the XR-2 bracket"></iframe>',
    effort: 'minutes',
    pitfalls: [
      'Titles must be unique across the page — two frames both titled "Video" fails a separate rule.',
      'A third-party embed you cannot edit still needs the title on your own <iframe> element, which you can always set.',
    ],
    platformNotes: {
      wordpress: 'oEmbed strips custom attributes. Use the raw HTML block for embeds that need a title.',
      react: 'Make `title` a required prop on any iframe wrapper component.',
    },
  },
  {
    ruleId: 'meta-viewport',
    title: 'Viewport that blocks zoom',
    problem: 'The viewport meta tag sets user-scalable=no, or a maximum-scale below 2, preventing the user from zooming.',
    impact: 'Users with low vision cannot enlarge the page. This is a single line of markup, copied from tutorial to tutorial for years, that disables a core assistive feature on every mobile device.',
    fix: [
      'Remove user-scalable=no and any maximum-scale below 5 entirely.',
      'The correct tag is: <meta name="viewport" content="width=device-width, initial-scale=1">.',
      'If zoom was disabled to stop iOS zooming on input focus, fix the cause instead: give form inputs a font-size of at least 16px.',
    ],
    wrong: '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">',
    right: '<meta name="viewport" content="width=device-width, initial-scale=1">',
    effort: 'minutes',
    pitfalls: [
      'Safari has ignored user-scalable=no since iOS 10, so the tag disables zoom only for the users who most need it — those on Android.',
    ],
    platformNotes: {
      wordpress: 'Usually hard-coded in the theme header.php.',
      react: 'Next.js App Router: the `viewport` export. Do not set maximumScale.',
    },
  },
] as const;

const BY_RULE = new Map(RECIPES.map((r) => [r.ruleId, r]));
export const recipeFor = (ruleId: string): Recipe | undefined => BY_RULE.get(ruleId);
export const hasRecipe = (ruleId: string): boolean => BY_RULE.has(ruleId);

/** Recipes that have a note for the platform, used to build the fix guides. */
export const recipesForPlatform = (id: PlatformId): Recipe[] =>
  RECIPES.filter((r) => r.platformNotes[id] !== undefined);
